### PR TITLE
French: Fix Burning Opal & Feral Lightning

### PR DESCRIPTION
**Pull request by loganmzz**
One guy from French community made a review and have found two issues. Here's new French data.

### CODE REVIEW

**Comment by on3iro** [comment]
@loganmzz oh nice. Thanks for the update. I  will release it with the next version of the randomizer (it will probably take a while)

**Comment by loganmzz** [comment]
Oh, I thought as you use a distinct repository, that you target to deliver data independently. Have you plan to do so ?

**Comment by on3iro** [comment]
@loganmzz no, the data is still delivered via randomizer versions. Our randomizer just uses this package under the hood.

The reasonings to split out data as its own package where:
1. we wanted to make the data easily available to others, who might want to build something, without them having to dig through our randomizer repository
2. we are starting to build stuff on top of this data as well as our randomizer, and therefore need the data elsewhere

If we would want to deliver the data independently we would have to  setup some form of API which we do not want to do at the moment. We want AER to come "batteries included" ;)

**Comment by loganmzz** [comment]
I haven't look at which CDN you were using but you can't create another path ? And then use lazy loading ? I'm not a PWA expert but I can ask to some people around me.

**Comment by on3iro** [comment]
no you misunderstand me - the files are currently bundled with all the other javascript. we deliver a single static website and don't use a CDN to provide the data at all.
We would have to make a few adjustments to make the data split work and to be honest this currenlty does not have real importance to me, as the other way works fine and I don't have much time to dedicate to the project at the moment.

I will try to make a  patch ready with the changes you provided during the next few days. I can't give you a more precise timeline as I am really busy atm :/

**Comment by loganmzz** [comment]
OK, no problem. If I have time I will look at your deployment :)

Regarding release, some guy in French community have provided content for Depths and Nameless. It could be nice if it can also be included in next release. I will do my best to provide it in coming days.

Have a nice day !

**Comment by on3iro** [comment]
@loganmzz awesome! Additional content is definitely release worthy. Thanks a lot for your work :)

**Pull request merged**
