### PR TITLE
on3iro/aeons-end-randomizer#298 Adds French data

### PR DESCRIPTION
**Pull request by loganmzz**
Data has been generated with: https://github.com/loganmzz/aeons-end-randomizer-data-generator

Datasource is a Google Sheet: https://docs.google.com/spreadsheets/d/1yxFwi77V6qzQ9xEKKIXkAWe9R7oBgnpphvoBRfpLcnA/edit?usp=sharing

### CODE REVIEW

**Comment by on3iro** [comment]
@loganmzz is this ready for review, or is there still something missing?

**Comment by loganmzz** [comment]
Currently there is only core box content. I still miss small expansions content from Wave 1. But we can add it later.

Ok, I will make the change later.

**Comment by loganmzz** [comment]
Sorry I miss this PR, I will modify my commit this evening.

**Comment by loganmzz** [comment]
Done, it's now ready for review !

**Comment by on3iro** [comment]
Awesome thanks for the contribution :+1: I will have a look at the PR over the upcoming weekend.

I aim to release the language support with version 3.1.0 . I hope to get 3.0.0 ready in the next couple of days and will start working on the language support afterwards, so it hopefully shouldn't take me too long to implement it.

**Pull request merged**
